# Generated by Django 3.2.8 on 2021-10-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_auto_20211029_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthousing',
            name='amenities',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studenthousing',
            name='deadline',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studenthousing',
            name='landlordEmail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studenthousing',
            name='landlordPhone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
