# Generated by Django 3.2.8 on 2021-11-07 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_studenthousing_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.studenthousing')),
            ],
        ),
    ]
