# Generated by Django 3.2.8 on 2021-11-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(default='', max_length=200),
        ),
    ]
