# Generated by Django 3.2.8 on 2021-11-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0008_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthousing',
            name='averageRating',
            field=models.FloatField(default=0),
        ),
    ]
