# Generated by Django 3.2.8 on 2021-11-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0012_auto_20211107_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedListings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingName', models.CharField(max_length=200)),
                ('listingAddress', models.CharField(max_length=500)),
            ],
        ),
    ]
