# Generated by Django 3.2.9 on 2021-11-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0013_suggestedlistings'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthousing',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenthousing',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
