# Generated by Django 3.2.8 on 2021-11-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0015_auto_20211115_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schoolYear',
            field=models.CharField(default='', max_length=50),
        ),
    ]
