# Generated by Django 3.2.8 on 2021-11-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0016_alter_user_schoolyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adddress', models.CharField(max_length=500)),
                ('picture', models.FileField(upload_to='media/')),
            ],
        ),
    ]
