# Generated by Django 3.2.8 on 2021-11-28 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0017_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHousingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='media/')),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.studenthousing')),
            ],
        ),
    ]
