# Generated by Django 3.2.8 on 2021-11-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0019_studenthousing_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenthousing',
            name='test',
        ),
    ]
