# Generated by Django 3.2.8 on 2021-11-28 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0020_remove_studenthousing_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthousing',
            name='photo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
