# Generated by Django 3.2.8 on 2021-11-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0021_studenthousing_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Storage',
        ),
        migrations.RemoveField(
            model_name='studenthousing',
            name='photo',
        ),
        migrations.DeleteModel(
            name='StudentHousingPhoto',
        ),
    ]
