# Generated by Django 3.2.7 on 2021-12-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0022_auto_20211128_1221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
