# Generated by Django 3.2.9 on 2021-12-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0023_auto_20211203_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestedlistings',
            old_name='Address',
            new_name='listingAddress',
        ),
        migrations.RenameField(
            model_name='suggestedlistings',
            old_name='Name',
            new_name='listingName',
        ),
    ]
