# Generated by Django 3.2.9 on 2021-12-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0024_auto_20211204_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestedlistings',
            old_name='listingAddress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='suggestedlistings',
            old_name='listingName',
            new_name='Name',
        ),
    ]
