# Generated by Django 3.2.8 on 2021-12-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0025_auto_20211204_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFavorite',
        ),
    ]
