# Generated by Django 3.2.8 on 2021-12-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0026_delete_userfavorite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
